import { EventLiveExplain } from 'src/types/domain/event-live-explain.type';

import {
  EventLiveExplainCreateInput,
  PrismaEventLiveExplain,
  PrismaEventLiveExplainCreateInput,
} from './types';

export const mapPrismaEventLiveExplainToDomain = (
  prismaEventLiveExplain: PrismaEventLiveExplain,
): EventLiveExplain => ({
  eventId: prismaEventLiveExplain.eventId,
  elementId: prismaEventLiveExplain.elementId,
  bps: prismaEventLiveExplain.bps,
  bonus: prismaEventLiveExplain.bonus,
  minutes: prismaEventLiveExplain.minutes,
  minutesPoints: prismaEventLiveExplain.minutesPoints,
  goalsScored: prismaEventLiveExplain.goalsScored,
  goalsScoredPoints: prismaEventLiveExplain.goalsScoredPoints,
  assists: prismaEventLiveExplain.assists,
  assistsPoints: prismaEventLiveExplain.assistsPoints,
  cleanSheets: prismaEventLiveExplain.cleanSheets,
  cleanSheetsPoints: prismaEventLiveExplain.cleanSheetsPoints,
  goalsConceded: prismaEventLiveExplain.goalsConceded,
  goalsConcededPoints: prismaEventLiveExplain.goalsConcededPoints,
  ownGoals: prismaEventLiveExplain.ownGoals,
  ownGoalsPoints: prismaEventLiveExplain.ownGoalsPoints,
  penaltiesSaved: prismaEventLiveExplain.penaltiesSaved,
  penaltiesSavedPoints: prismaEventLiveExplain.penaltiesSavedPoints,
  penaltiesMissed: prismaEventLiveExplain.penaltiesMissed,
  penaltiesMissedPoints: prismaEventLiveExplain.penaltiesMissedPoints,
  yellowCards: prismaEventLiveExplain.yellowCards,
  yellowCardsPoints: prismaEventLiveExplain.yellowCardsPoints,
  redCards: prismaEventLiveExplain.redCards,
  redCardsPoints: prismaEventLiveExplain.redCardsPoints,
  saves: prismaEventLiveExplain.saves,
  savesPoints: prismaEventLiveExplain.savesPoints,
  mngWin: prismaEventLiveExplain.mngWin,
  mngWinPoints: prismaEventLiveExplain.mngWinPoints,
  mngDraw: prismaEventLiveExplain.mngDraw,
  mngDrawPoints: prismaEventLiveExplain.mngDrawPoints,
  mngLoss: prismaEventLiveExplain.mngLoss,
  mngLossPoints: prismaEventLiveExplain.mngLossPoints,
  mngUnderdogWin: prismaEventLiveExplain.mngUnderdogWin,
  mngUnderdogWinPoints: prismaEventLiveExplain.mngUnderdogWinPoints,
  mngUnderdogDraw: prismaEventLiveExplain.mngUnderdogDraw,
  mngUnderdogDrawPoints: prismaEventLiveExplain.mngUnderdogDrawPoints,
  mngCleanSheets: prismaEventLiveExplain.mngCleanSheets,
  mngCleanSheetsPoints: prismaEventLiveExplain.mngCleanSheetsPoints,
  mngGoalsScored: prismaEventLiveExplain.mngGoalsScored,
  mngGoalsScoredPoints: prismaEventLiveExplain.mngGoalsScoredPoints,
});

export const mapDomainEventLiveExplainToPrismaCreate = (
  domainEventLiveExplain: EventLiveExplainCreateInput,
): PrismaEventLiveExplainCreateInput => ({
  eventId: domainEventLiveExplain.eventId,
  elementId: domainEventLiveExplain.elementId,
  bps: domainEventLiveExplain.bps,
  bonus: domainEventLiveExplain.bonus,
  minutes: domainEventLiveExplain.minutes,
  minutesPoints: domainEventLiveExplain.minutesPoints,
  goalsScored: domainEventLiveExplain.goalsScored,
  goalsScoredPoints: domainEventLiveExplain.goalsScoredPoints,
  assists: domainEventLiveExplain.assists,
  assistsPoints: domainEventLiveExplain.assistsPoints,
  cleanSheets: domainEventLiveExplain.cleanSheets,
  cleanSheetsPoints: domainEventLiveExplain.cleanSheetsPoints,
  goalsConceded: domainEventLiveExplain.goalsConceded,
  goalsConcededPoints: domainEventLiveExplain.goalsConcededPoints,
  ownGoals: domainEventLiveExplain.ownGoals,
  ownGoalsPoints: domainEventLiveExplain.ownGoalsPoints,
  penaltiesSaved: domainEventLiveExplain.penaltiesSaved,
  penaltiesSavedPoints: domainEventLiveExplain.penaltiesSavedPoints,
  penaltiesMissed: domainEventLiveExplain.penaltiesMissed,
  penaltiesMissedPoints: domainEventLiveExplain.penaltiesMissedPoints,
  yellowCards: domainEventLiveExplain.yellowCards,
  yellowCardsPoints: domainEventLiveExplain.yellowCardsPoints,
  redCards: domainEventLiveExplain.redCards,
  redCardsPoints: domainEventLiveExplain.redCardsPoints,
  saves: domainEventLiveExplain.saves,
  savesPoints: domainEventLiveExplain.savesPoints,
  mngWin: domainEventLiveExplain.mngWin,
  mngWinPoints: domainEventLiveExplain.mngWinPoints,
  mngDraw: domainEventLiveExplain.mngDraw,
  mngDrawPoints: domainEventLiveExplain.mngDrawPoints,
  mngLoss: domainEventLiveExplain.mngLoss,
  mngLossPoints: domainEventLiveExplain.mngLossPoints,
  mngUnderdogWin: domainEventLiveExplain.mngUnderdogWin,
  mngUnderdogWinPoints: domainEventLiveExplain.mngUnderdogWinPoints,
  mngUnderdogDraw: domainEventLiveExplain.mngUnderdogDraw,
  mngUnderdogDrawPoints: domainEventLiveExplain.mngUnderdogDrawPoints,
  mngCleanSheets: domainEventLiveExplain.mngCleanSheets,
  mngCleanSheetsPoints: domainEventLiveExplain.mngCleanSheetsPoints,
  mngGoalsScored: domainEventLiveExplain.mngGoalsScored,
  mngGoalsScoredPoints: domainEventLiveExplain.mngGoalsScoredPoints,
});
