import {
  EventLiveExplainCreateInput,
  DbEventLiveExplain,
  DbEventLiveExplainCreateInput,
} from 'repositories/event-live-explain/types';
import { EventLiveExplain } from 'types/domain/event-live-explain.type';
import { EventId } from 'types/domain/event.type';
import { PlayerId } from 'types/domain/player.type';

export const mapDbEventLiveExplainToDomain = (
  dbEventLiveExplain: DbEventLiveExplain,
): EventLiveExplain => ({
  eventId: dbEventLiveExplain.eventId as EventId,
  elementId: dbEventLiveExplain.elementId as PlayerId,
  bonus: dbEventLiveExplain.bonus,
  minutes: dbEventLiveExplain.minutes,
  minutesPoints: dbEventLiveExplain.minutesPoints,
  goalsScored: dbEventLiveExplain.goalsScored,
  goalsScoredPoints: dbEventLiveExplain.goalsScoredPoints,
  assists: dbEventLiveExplain.assists,
  assistsPoints: dbEventLiveExplain.assistsPoints,
  cleanSheets: dbEventLiveExplain.cleanSheets,
  cleanSheetsPoints: dbEventLiveExplain.cleanSheetsPoints,
  goalsConceded: dbEventLiveExplain.goalsConceded,
  goalsConcededPoints: dbEventLiveExplain.goalsConcededPoints,
  ownGoals: dbEventLiveExplain.ownGoals,
  ownGoalsPoints: dbEventLiveExplain.ownGoalsPoints,
  penaltiesSaved: dbEventLiveExplain.penaltiesSaved,
  penaltiesSavedPoints: dbEventLiveExplain.penaltiesSavedPoints,
  penaltiesMissed: dbEventLiveExplain.penaltiesMissed,
  penaltiesMissedPoints: dbEventLiveExplain.penaltiesMissedPoints,
  yellowCards: dbEventLiveExplain.yellowCards,
  yellowCardsPoints: dbEventLiveExplain.yellowCardsPoints,
  redCards: dbEventLiveExplain.redCards,
  redCardsPoints: dbEventLiveExplain.redCardsPoints,
  saves: dbEventLiveExplain.saves,
  savesPoints: dbEventLiveExplain.savesPoints,
  mngWin: dbEventLiveExplain.mngWin,
  mngWinPoints: dbEventLiveExplain.mngWinPoints,
  mngDraw: dbEventLiveExplain.mngDraw,
  mngDrawPoints: dbEventLiveExplain.mngDrawPoints,
  mngLoss: dbEventLiveExplain.mngLoss,
  mngLossPoints: dbEventLiveExplain.mngLossPoints,
  mngUnderdogWin: dbEventLiveExplain.mngUnderdogWin,
  mngUnderdogWinPoints: dbEventLiveExplain.mngUnderdogWinPoints,
  mngUnderdogDraw: dbEventLiveExplain.mngUnderdogDraw,
  mngUnderdogDrawPoints: dbEventLiveExplain.mngUnderdogDrawPoints,
  mngCleanSheets: dbEventLiveExplain.mngCleanSheets,
  mngCleanSheetsPoints: dbEventLiveExplain.mngCleanSheetsPoints,
  mngGoalsScored: dbEventLiveExplain.mngGoalsScored,
  mngGoalsScoredPoints: dbEventLiveExplain.mngGoalsScoredPoints,
});

export const mapDomainEventLiveExplainToDbCreate = (
  domainEventLiveExplain: EventLiveExplainCreateInput,
): DbEventLiveExplainCreateInput => ({
  eventId: domainEventLiveExplain.eventId,
  elementId: domainEventLiveExplain.elementId,
  bonus: domainEventLiveExplain.bonus,
  minutes: domainEventLiveExplain.minutes,
  minutesPoints: domainEventLiveExplain.minutesPoints,
  goalsScored: domainEventLiveExplain.goalsScored,
  goalsScoredPoints: domainEventLiveExplain.goalsScoredPoints,
  assists: domainEventLiveExplain.assists,
  assistsPoints: domainEventLiveExplain.assistsPoints,
  cleanSheets: domainEventLiveExplain.cleanSheets,
  cleanSheetsPoints: domainEventLiveExplain.cleanSheetsPoints,
  goalsConceded: domainEventLiveExplain.goalsConceded,
  goalsConcededPoints: domainEventLiveExplain.goalsConcededPoints,
  ownGoals: domainEventLiveExplain.ownGoals,
  ownGoalsPoints: domainEventLiveExplain.ownGoalsPoints,
  penaltiesSaved: domainEventLiveExplain.penaltiesSaved,
  penaltiesSavedPoints: domainEventLiveExplain.penaltiesSavedPoints,
  penaltiesMissed: domainEventLiveExplain.penaltiesMissed,
  penaltiesMissedPoints: domainEventLiveExplain.penaltiesMissedPoints,
  yellowCards: domainEventLiveExplain.yellowCards,
  yellowCardsPoints: domainEventLiveExplain.yellowCardsPoints,
  redCards: domainEventLiveExplain.redCards,
  redCardsPoints: domainEventLiveExplain.redCardsPoints,
  saves: domainEventLiveExplain.saves,
  savesPoints: domainEventLiveExplain.savesPoints,
  mngWin: domainEventLiveExplain.mngWin,
  mngWinPoints: domainEventLiveExplain.mngWinPoints,
  mngDraw: domainEventLiveExplain.mngDraw,
  mngDrawPoints: domainEventLiveExplain.mngDrawPoints,
  mngLoss: domainEventLiveExplain.mngLoss,
  mngLossPoints: domainEventLiveExplain.mngLossPoints,
  mngUnderdogWin: domainEventLiveExplain.mngUnderdogWin,
  mngUnderdogWinPoints: domainEventLiveExplain.mngUnderdogWinPoints,
  mngUnderdogDraw: domainEventLiveExplain.mngUnderdogDraw,
  mngUnderdogDrawPoints: domainEventLiveExplain.mngUnderdogDrawPoints,
  mngCleanSheets: domainEventLiveExplain.mngCleanSheets,
  mngCleanSheetsPoints: domainEventLiveExplain.mngCleanSheetsPoints,
  mngGoalsScored: domainEventLiveExplain.mngGoalsScored,
  mngGoalsScoredPoints: domainEventLiveExplain.mngGoalsScoredPoints,
});
