-- Tournament setup reliability and capability-aware diagnostics.
-- This migration is additive. Existing setup status/phase enum values remain
-- unchanged so older workers can continue to read the rows during rollout.

ALTER TABLE competition.tournaments
    ADD COLUMN IF NOT EXISTS setup_attempt integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS setup_max_attempts integer NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS setup_next_retry_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS setup_last_error_code text,
    ADD COLUMN IF NOT EXISTS setup_last_error_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS setup_progress_indeterminate boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS profiles_ready_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS insights_ready_at timestamp with time zone;

ALTER TABLE competition.tournaments
    DROP CONSTRAINT IF EXISTS tournaments_setup_attempts_valid;

ALTER TABLE competition.tournaments
    ADD CONSTRAINT tournaments_setup_attempts_valid
    CHECK (setup_attempt >= 0 AND setup_max_attempts >= 1 AND setup_attempt <= setup_max_attempts);

COMMENT ON COLUMN competition.tournaments.setup_attempt IS
    'Current setup attempt number. Retryable failures remain PROCESSING until the final attempt.';
COMMENT ON COLUMN competition.tournaments.setup_max_attempts IS
    'Maximum attempts allowed by the setup worker policy.';
COMMENT ON COLUMN competition.tournaments.setup_progress_indeterminate IS
    'True when progress cannot be represented as a determinate unit count.';
COMMENT ON COLUMN competition.tournaments.profiles_ready_at IS
    'Timestamp at which participant and source league profile data was complete.';
COMMENT ON COLUMN competition.tournaments.insights_ready_at IS
    'Timestamp at which historical, selection and result insights were complete.';

CREATE TABLE IF NOT EXISTS competition.tournament_setup_issues (
    issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id smallint NOT NULL,
    tournament_id integer NOT NULL,
    issue_key text NOT NULL,
    code text NOT NULL,
    category text NOT NULL,
    severity text NOT NULL,
    event_id integer,
    affected_entry_ids integer[] NOT NULL DEFAULT '{}'::integer[],
    affected_entry_count integer NOT NULL DEFAULT 0,
    diagnostic_code text,
    internal_message text,
    repair_attempts integer NOT NULL DEFAULT 0,
    next_repair_at timestamp with time zone,
    repair_exhausted_at timestamp with time zone,
    first_seen_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tournament_setup_issues_tournament_fk
        FOREIGN KEY (season_id, tournament_id)
        REFERENCES competition.tournaments (season_id, tournament_id)
        ON DELETE CASCADE,
    CONSTRAINT tournament_setup_issues_scope_unique
        UNIQUE (season_id, tournament_id, issue_key),
    CONSTRAINT tournament_setup_issues_category_valid
        CHECK (category IN ('profiles', 'insights', 'results')),
    CONSTRAINT tournament_setup_issues_code_valid
        CHECK (code IN (
            'ENTRY_PROFILE_INCOMPLETE',
            'ENTRY_HISTORY_INCOMPLETE',
            'LEAGUE_INSIGHTS_INCOMPLETE',
            'SELECTION_INSIGHTS_INCOMPLETE',
            'TOURNAMENT_RESULTS_INCOMPLETE',
            'STRUCTURE_INTEGRITY_FAILED'
        )),
    CONSTRAINT tournament_setup_issues_severity_valid
        CHECK (severity IN ('warning', 'blocking')),
    CONSTRAINT tournament_setup_issues_key_nonempty
        CHECK (btrim(issue_key) <> '' AND btrim(code) <> ''),
    CONSTRAINT tournament_setup_issues_counts_valid
        CHECK (
            affected_entry_count >= 0 AND
            repair_attempts >= 0 AND
            affected_entry_count = cardinality(affected_entry_ids)
        )
);

CREATE INDEX IF NOT EXISTS tournament_setup_issues_unresolved_idx
    ON competition.tournament_setup_issues (season_id, tournament_id, category, severity)
    WHERE resolved_at IS NULL;

CREATE INDEX IF NOT EXISTS tournament_setup_issues_repair_due_idx
    ON competition.tournament_setup_issues (next_repair_at, season_id, tournament_id)
    WHERE resolved_at IS NULL AND repair_exhausted_at IS NULL AND next_repair_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS tournament_setup_issues_event_idx
    ON competition.tournament_setup_issues (season_id, tournament_id, event_id)
    WHERE resolved_at IS NULL AND event_id IS NOT NULL;

COMMENT ON TABLE competition.tournament_setup_issues IS
    'Deduplicated, capability-scoped setup diagnostics and automatic repair state.';

-- Existing clean READY rows get explicit capability timestamps without
-- interpreting legacy warning text. The reconciliation worker will audit old
-- READY-with-warning rows and create structured issues after deployment.
UPDATE competition.tournaments
SET
    profiles_ready_at = COALESCE(profiles_ready_at, setup_finished_at),
    insights_ready_at = COALESCE(insights_ready_at, setup_finished_at)
WHERE setup_status = 'ready'
  AND setup_warning_count = 0
  AND setup_finished_at IS NOT NULL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE competition.tournament_setup_issues TO letletme_data_writer;
GRANT SELECT
    ON TABLE competition.tournament_setup_issues TO letletme_graphql_reader;
GRANT USAGE, SELECT
    ON SEQUENCE competition.tournament_setup_issues_issue_id_seq TO letletme_data_writer;
