-- ============================================================================
-- Align fresh-database columns with TypeScript Drizzle schemas
-- ============================================================================
-- Journaled migration 0005 dropped `updated_at` from several tables and never
-- created it on others (entry_infos, entry_event_transfers, …). App repositories
-- still write these columns via `...timestamps` / onConflict updates, so
-- `db:migrate` + `db:apply-sql` on an empty Postgres left CI integration broken
-- with "column updated_at does not exist" / "last_event_id does not exist".
--
-- Idempotent: safe on production DBs that already have the columns.
-- ============================================================================

-- Re-add columns removed by 0005_easy_zarda.sql
ALTER TABLE teams ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE players ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE phases ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- entry_infos: schema has timestamps + last_event_id (never journaled)
ALTER TABLE entry_infos ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE entry_infos ADD COLUMN IF NOT EXISTS last_event_id integer DEFAULT 0;

ALTER TABLE entry_league_infos ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE entry_history_infos ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- Entry event tables created without updated_at in 0005
ALTER TABLE entry_event_picks ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE entry_event_transfers ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- Live tables (after 0006 renames event_live → event_lives)
ALTER TABLE IF EXISTS event_lives ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE IF EXISTS event_live_explains ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- FPL past-season labels are "YYYY/YY" (7 chars); journaled 0005 used char(4).
ALTER TABLE entry_history_infos
  ALTER COLUMN season TYPE char(7);

-- player_stats was created in 0002 with denormalized NOT NULL columns the app
-- no longer writes (web_name, team_name, …). Drop them so upserts match the
-- current Drizzle schema.
ALTER TABLE player_stats DROP COLUMN IF EXISTS web_name;
ALTER TABLE player_stats DROP COLUMN IF EXISTS element_type_name;
ALTER TABLE player_stats DROP COLUMN IF EXISTS team_name;
ALTER TABLE player_stats DROP COLUMN IF EXISTS team_short_name;
ALTER TABLE player_stats DROP COLUMN IF EXISTS value;
-- team_id remains on some DBs from 0002; schema no longer maps it.
ALTER TABLE player_stats DROP COLUMN IF EXISTS team_id;

-- Upserts that re-insert rows selected earlier include explicit `id` values.
-- GENERATED ALWAYS rejects those; BY DEFAULT allows explicit ids when needed.
-- Skip tables that use SERIAL (not IDENTITY) or have no identity column.
DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'tournament_battle_group_results',
    'tournament_points_group_results',
    'tournament_knockout_results',
    'tournament_knockouts',
    'tournament_groups',
    'tournament_entries',
    'entry_event_picks',
    'entry_event_transfers',
    'entry_event_results',
    'entry_league_infos',
    'entry_history_infos',
    'event_lives',
    'event_live_explains',
    'event_live_summaries',
    'player_stats',
    'player_values'
  ];
BEGIN
  FOREACH t IN ARRAY tables
  LOOP
    BEGIN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
    EXCEPTION
      WHEN undefined_table THEN
        RAISE NOTICE 'skip identity alter, missing table %', t;
      WHEN undefined_column THEN
        RAISE NOTICE 'skip identity alter, no id on %', t;
      WHEN others THEN
        -- e.g. SERIAL columns: "is not an identity column"
        RAISE NOTICE 'skip identity alter on %: %', t, SQLERRM;
    END;
  END LOOP;
END $$;
