-- Queue governance control plane.  These tables contain bounded operational
-- evidence only; raw payloads, credentials and per-attempt history remain in
-- Bull retained failures/structured logs.

CREATE OR REPLACE FUNCTION ops.entry_is_eligible_for_event(
  p_started_event integer,
  p_event_id integer
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_started_event IS NULL OR p_started_event <= p_event_id
$$;

CREATE TABLE ops.queue_health_windows (
  window_start timestamptz NOT NULL,
  queue_name text NOT NULL,
  waiting integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 0,
  delayed integer NOT NULL DEFAULT 0,
  prioritized integer NOT NULL DEFAULT 0,
  waiting_children integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0,
  completed integer NOT NULL DEFAULT 0,
  runnable integer NOT NULL DEFAULT 0,
  oldest_runnable_age_ms bigint,
  arrivals integer NOT NULL DEFAULT 0,
  completions integer NOT NULL DEFAULT 0,
  failures integer NOT NULL DEFAULT 0,
  stalled integer NOT NULL DEFAULT 0,
  wait_p50_ms bigint,
  wait_p95_ms bigint,
  execution_p50_ms bigint,
  execution_p95_ms bigint,
  provider_wait_p95_ms bigint,
  provider_429_rate numeric(6,5),
  net_growth integer NOT NULL DEFAULT 0,
  drain_eta_ms bigint,
  backlog_class text NOT NULL DEFAULT 'HEALTHY',
  admission_mode text NOT NULL DEFAULT 'OPEN',
  consumer_heartbeat_at timestamptz,
  release_sha text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT queue_health_windows_pk PRIMARY KEY (window_start, queue_name),
  CONSTRAINT queue_health_windows_queue_nonempty CHECK (btrim(queue_name) <> ''),
  CONSTRAINT queue_health_windows_counts_nonnegative CHECK (
    waiting >= 0 AND active >= 0 AND delayed >= 0 AND prioritized >= 0
    AND waiting_children >= 0 AND failed >= 0 AND completed >= 0 AND runnable >= 0
    AND arrivals >= 0 AND completions >= 0 AND failures >= 0 AND stalled >= 0
  ),
  CONSTRAINT queue_health_windows_backlog_class_check CHECK (
    backlog_class IN ('NO_CONSUMER','POISON_STORM','STALLED','DEADLINE_RISK',
                      'PROVIDER_THROTTLED','BURST','HEALTHY')
  ),
  CONSTRAINT queue_health_windows_admission_check CHECK (admission_mode IN ('OPEN','DRAIN_ONLY')),
  CONSTRAINT queue_health_windows_evidence_object CHECK (jsonb_typeof(evidence) = 'object')
);

CREATE INDEX queue_health_windows_queue_time_idx
  ON ops.queue_health_windows (queue_name, window_start DESC);
CREATE INDEX queue_health_windows_class_time_idx
  ON ops.queue_health_windows (backlog_class, window_start DESC)
  WHERE backlog_class <> 'HEALTHY';

CREATE TABLE ops.data_governance_cases (
  case_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_kind text NOT NULL,
  contract_key text NOT NULL,
  lane text NOT NULL,
  obligation_id uuid,
  slo_window_id bigint,
  scope_key text NOT NULL,
  target_revision text,
  error_class text NOT NULL,
  error_code text NOT NULL,
  fingerprint text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  repair_target jsonb NOT NULL DEFAULT '{}'::jsonb,
  compensator text NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'OPEN',
  last_error text,
  opened_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  recovered_at timestamptz,
  recovery_revision text,
  CONSTRAINT data_governance_cases_status_check CHECK (
    status IN ('OPEN','AUTO_REPAIRING','REQUIRES_REVIEW','RECOVERED','DISMISSED')
  ),
  CONSTRAINT data_governance_cases_attempts_check CHECK (attempts >= 0),
  CONSTRAINT data_governance_cases_key_check CHECK (
    btrim(case_kind) <> '' AND btrim(contract_key) <> '' AND btrim(lane) <> ''
    AND btrim(scope_key) <> '' AND btrim(error_class) <> '' AND btrim(error_code) <> ''
    AND btrim(fingerprint) <> '' AND btrim(compensator) <> ''
  ),
  CONSTRAINT data_governance_cases_evidence_object CHECK (jsonb_typeof(evidence) = 'object'),
  CONSTRAINT data_governance_cases_repair_object CHECK (jsonb_typeof(repair_target) = 'object')
);

CREATE UNIQUE INDEX data_governance_cases_open_dedupe_idx
  ON ops.data_governance_cases (case_kind, contract_key, lane, scope_key, fingerprint)
  WHERE status IN ('OPEN','AUTO_REPAIRING','REQUIRES_REVIEW');
CREATE INDEX data_governance_cases_status_time_idx
  ON ops.data_governance_cases (status, updated_at DESC);
CREATE INDEX data_governance_cases_slo_idx
  ON ops.data_governance_cases (slo_window_id)
  WHERE slo_window_id IS NOT NULL;
CREATE INDEX data_governance_cases_obligation_idx
  ON ops.data_governance_cases (obligation_id)
  WHERE obligation_id IS NOT NULL;

REVOKE ALL ON TABLE ops.queue_health_windows FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ops.queue_health_windows TO letletme_data_writer;
REVOKE ALL ON TABLE ops.data_governance_cases FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON TABLE ops.data_governance_cases TO letletme_data_writer;
GRANT USAGE, SELECT ON SEQUENCE ops.data_governance_cases_case_id_seq TO letletme_data_writer;
REVOKE ALL ON FUNCTION ops.entry_is_eligible_for_event(integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ops.entry_is_eligible_for_event(integer, integer) TO letletme_data_writer;
REVOKE ALL ON TABLE ops.queue_health_windows FROM letletme_graphql_reader;
REVOKE ALL ON TABLE ops.data_governance_cases FROM letletme_graphql_reader;
