CREATE TABLE ops.freshness_slo_windows (
  window_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slo_key text NOT NULL,
  contract_key text NOT NULL,
  season_id smallint,
  scope_key text NOT NULL,
  period_key text NOT NULL,
  event_id integer,
  source_day date,
  eligible_at timestamptz NOT NULL,
  due_at timestamptz NOT NULL,
  obligation_due_at timestamptz,
  source_checked_at timestamptz,
  pg_published_at timestamptz,
  redis_seen_at timestamptz,
  graphql_seen_at timestamptz,
  web_seen_at timestamptz,
  producer_revision text,
  redis_revision text,
  graphql_revision text,
  web_revision text,
  expected_count integer,
  observed_count integer,
  not_applicable_count integer NOT NULL DEFAULT 0,
  completeness_status text NOT NULL DEFAULT 'PENDING',
  status text NOT NULL DEFAULT 'PENDING',
  breach_code text,
  recovered_at timestamptz,
  recovery_revision text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT freshness_slo_windows_identity UNIQUE (slo_key, scope_key, period_key),
  CONSTRAINT freshness_slo_windows_status_check CHECK (
    status IN ('PENDING','MET','BREACHED','INVALID','NOT_APPLICABLE')
  ),
  CONSTRAINT freshness_slo_windows_completeness_check CHECK (
    completeness_status IN ('PENDING','COMPLETE','INCOMPLETE','INVALID','NOT_APPLICABLE')
  ),
  CONSTRAINT freshness_slo_windows_counts_check CHECK (
    (expected_count IS NULL OR expected_count >= 0)
    AND (observed_count IS NULL OR observed_count >= 0)
    AND not_applicable_count >= 0
  ),
  CONSTRAINT freshness_slo_windows_time_check CHECK (due_at >= eligible_at),
  CONSTRAINT freshness_slo_windows_evidence_object CHECK (jsonb_typeof(evidence) = 'object')
);

CREATE INDEX freshness_slo_windows_pending_due_idx
  ON ops.freshness_slo_windows (due_at, window_id)
  WHERE status = 'PENDING';
CREATE INDEX freshness_slo_windows_breach_idx
  ON ops.freshness_slo_windows (contract_key, status, due_at DESC)
  WHERE status IN ('BREACHED','INVALID');
CREATE INDEX freshness_slo_windows_scope_idx
  ON ops.freshness_slo_windows (season_id, event_id, contract_key, due_at DESC);

REVOKE ALL ON TABLE ops.freshness_slo_windows FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON TABLE ops.freshness_slo_windows TO letletme_data_writer;
GRANT USAGE, SELECT ON SEQUENCE ops.freshness_slo_windows_window_id_seq TO letletme_data_writer;
REVOKE ALL ON TABLE ops.freshness_slo_windows FROM letletme_graphql_reader;
