-- Anonymous client telemetry. Raw request bodies, identities, URLs and error
-- text are deliberately not persisted; only bounded five-minute aggregates
-- and a short-lived batch idempotency ledger are retained.

CREATE TABLE ops.client_signal_batches (
  batch_id uuid NOT NULL,
  client text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  batch_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CONSTRAINT client_signal_batches_client_check
    CHECK (client IN ('web', 'wechat_miniprogram'))
);

CREATE UNIQUE INDEX client_signal_batches_batch_id_unique
  ON ops.client_signal_batches (batch_id);
CREATE INDEX client_signal_batches_received_idx
  ON ops.client_signal_batches (received_at DESC);

CREATE TABLE ops.client_signal_windows (
  window_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start timestamptz NOT NULL,
  client text NOT NULL,
  release text NOT NULL,
  surface text NOT NULL,
  metric text NOT NULL,
  device_group text NOT NULL,
  sample_source text NOT NULL,
  result text NOT NULL,
  bucket text NOT NULL,
  sample_count bigint NOT NULL DEFAULT 0,
  value_sum double precision NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT client_signal_windows_client_check
    CHECK (client IN ('web', 'wechat_miniprogram')),
  CONSTRAINT client_signal_windows_source_check
    CHECK (sample_source IN ('real', 'synthetic')),
  CONSTRAINT client_signal_windows_result_check
    CHECK (result IN ('ok', 'error', 'timeout', 'auth_error', 'stale', 'unavailable')),
  CONSTRAINT client_signal_windows_count_check CHECK (sample_count > 0),
  CONSTRAINT client_signal_windows_value_check CHECK (value_sum >= 0),
  CONSTRAINT client_signal_windows_dimensions_check CHECK (
    btrim(release) <> '' AND btrim(surface) <> '' AND btrim(metric) <> ''
    AND btrim(device_group) <> '' AND btrim(bucket) <> ''
  )
);

CREATE UNIQUE INDEX client_signal_windows_identity
  ON ops.client_signal_windows (
    window_start, client, release, surface, metric, device_group,
    sample_source, result, bucket
  );
CREATE INDEX client_signal_windows_client_metric_time_idx
  ON ops.client_signal_windows (client, metric, window_start DESC);
CREATE INDEX client_signal_windows_retention_idx
  ON ops.client_signal_windows (window_start);

REVOKE ALL ON TABLE ops.client_signal_batches FROM PUBLIC;
GRANT SELECT, INSERT, DELETE ON TABLE ops.client_signal_batches TO letletme_data_writer;
GRANT USAGE, SELECT ON SEQUENCE ops.client_signal_batches_batch_row_id_seq TO letletme_data_writer;
REVOKE ALL ON TABLE ops.client_signal_batches FROM letletme_graphql_reader;

REVOKE ALL ON TABLE ops.client_signal_windows FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ops.client_signal_windows TO letletme_data_writer;
GRANT USAGE, SELECT ON SEQUENCE ops.client_signal_windows_window_id_seq TO letletme_data_writer;
REVOKE ALL ON TABLE ops.client_signal_windows FROM letletme_graphql_reader;
