-- V3 runtime inserts need durable surrogate source-row identities after the one-time v2 copy.
-- This file deliberately sorts after 0090 activation and before approval-gated 0091 cleanup.
-- GENERATED BY DEFAULT preserves every migrated ID while allowing new provider rows to omit it.

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '5min';
SET LOCAL ROLE letletme_data_owner;

ALTER TABLE competition.entry_season_histories
  ALTER COLUMN source_history_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME competition.entry_season_histories_source_history_id_seq);
ALTER TABLE competition.entry_leagues
  ALTER COLUMN source_entry_league_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME competition.entry_leagues_source_entry_league_id_seq);
ALTER TABLE competition.entry_event_picks
  ALTER COLUMN source_pick_row_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME competition.entry_event_picks_source_pick_row_id_seq);
ALTER TABLE competition.entry_event_results
  ALTER COLUMN source_result_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME competition.entry_event_results_source_result_id_seq);
ALTER TABLE competition.entry_event_cup_results
  ALTER COLUMN source_result_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME competition.entry_event_cup_results_source_result_id_seq);

ALTER TABLE fpl.player_event_snapshots
  ALTER COLUMN source_snapshot_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME fpl.player_event_snapshots_source_snapshot_id_seq);
ALTER TABLE fpl.player_gameweek_stats
  ALTER COLUMN source_live_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME fpl.player_gameweek_stats_source_live_id_seq);
ALTER TABLE fpl.player_gameweek_scoring_items
  ALTER COLUMN source_explain_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME fpl.player_gameweek_scoring_items_source_explain_id_seq);
ALTER TABLE fpl.player_fixture_stats
  ALTER COLUMN source_fixture_stat_id ADD GENERATED BY DEFAULT AS IDENTITY
    (SEQUENCE NAME fpl.player_fixture_stats_source_fixture_stat_id_seq);
-- Legacy value-seed rows intentionally have a NULL source_snapshot_id, so this column cannot be
-- an identity (identity columns are implicitly NOT NULL). A sequence-backed default allocates
-- identities for new upstream captures while preserving those provenance-bearing NULLs.
CREATE SEQUENCE fpl.player_market_snapshots_source_snapshot_id_seq;
ALTER SEQUENCE fpl.player_market_snapshots_source_snapshot_id_seq
  OWNED BY fpl.player_market_snapshots.source_snapshot_id;
ALTER TABLE fpl.player_market_snapshots
  ALTER COLUMN source_snapshot_id
  SET DEFAULT nextval('fpl.player_market_snapshots_source_snapshot_id_seq');

SELECT setval(
  pg_get_serial_sequence('competition.entry_season_histories', 'source_history_id'),
  COALESCE(MAX(source_history_id), 0) + 1,
  false
) FROM competition.entry_season_histories;
SELECT setval(
  pg_get_serial_sequence('competition.entry_leagues', 'source_entry_league_id'),
  COALESCE(MAX(source_entry_league_id), 0) + 1,
  false
) FROM competition.entry_leagues;
SELECT setval(
  pg_get_serial_sequence('competition.entry_event_picks', 'source_pick_row_id'),
  COALESCE(MAX(source_pick_row_id), 0) + 1,
  false
) FROM competition.entry_event_picks;
SELECT setval(
  pg_get_serial_sequence('competition.entry_event_results', 'source_result_id'),
  COALESCE(MAX(source_result_id), 0) + 1,
  false
) FROM competition.entry_event_results;
SELECT setval(
  pg_get_serial_sequence('competition.entry_event_cup_results', 'source_result_id'),
  COALESCE(MAX(source_result_id), 0) + 1,
  false
) FROM competition.entry_event_cup_results;
SELECT setval(
  pg_get_serial_sequence('fpl.player_event_snapshots', 'source_snapshot_id'),
  COALESCE(MAX(source_snapshot_id), 0) + 1,
  false
) FROM fpl.player_event_snapshots;
SELECT setval(
  pg_get_serial_sequence('fpl.player_gameweek_stats', 'source_live_id'),
  COALESCE(MAX(source_live_id), 0) + 1,
  false
) FROM fpl.player_gameweek_stats;
SELECT setval(
  pg_get_serial_sequence('fpl.player_gameweek_scoring_items', 'source_explain_id'),
  COALESCE(MAX(source_explain_id), 0) + 1,
  false
) FROM fpl.player_gameweek_scoring_items;
SELECT setval(
  pg_get_serial_sequence('fpl.player_fixture_stats', 'source_fixture_stat_id'),
  COALESCE(MAX(source_fixture_stat_id), 0) + 1,
  false
) FROM fpl.player_fixture_stats;
SELECT setval(
  pg_get_serial_sequence('fpl.player_market_snapshots', 'source_snapshot_id'),
  COALESCE(MAX(source_snapshot_id), 0) + 1,
  false
) FROM fpl.player_market_snapshots;

-- Runtime UPSERT/replacement keys must be enforced by PostgreSQL, not only by service code.
ALTER TABLE competition.tournaments
  ADD CONSTRAINT tournaments_name_key UNIQUE (season_id, name);

ALTER TABLE competition.entry_event_cup_results
  ADD CONSTRAINT entry_event_cup_results_business_unique
    UNIQUE (season_id, entry_id, event_id);

ALTER TABLE competition.entry_event_transfers
  ADD CONSTRAINT entry_event_transfers_business_unique
    UNIQUE NULLS NOT DISTINCT (
      season_id,
      entry_id,
      event_id,
      element_in_id,
      element_out_id,
      transfer_time
    );

ALTER TABLE competition.tournament_battle_group_results
  ADD CONSTRAINT tournament_battle_group_results_business_unique
    UNIQUE (tournament_id, group_id, event_id, home_index, away_index);

RESET ROLE;
