BEGIN;

SET LOCAL lock_timeout = '5s';

-- Freshness probes only need the newest row for a season. Keep the existing
-- max(updated_at) semantics while allowing PostgreSQL to stop at the first
-- matching entry in each season.
CREATE INDEX player_gameweek_stats_season_updated_idx
  ON fpl.player_gameweek_stats (season_id ASC, updated_at DESC NULLS LAST);
CREATE INDEX player_season_summary_rows_season_source_updated_idx
  ON reporting.player_season_summary_rows (season_id ASC, source_updated_at DESC NULLS LAST);

-- v2 is additive. The v1 tables remain untouched for installed clients and
-- their historical sample-only interpretation.
CREATE TABLE ops.client_signal_v2_batches (
  batch_id uuid NOT NULL,
  client text NOT NULL,
  client_release text NOT NULL,
  ingest_release text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  batch_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CONSTRAINT client_signal_v2_batches_client_check
    CHECK (client IN ('web', 'wechat_miniprogram')),
  CONSTRAINT client_signal_v2_batches_client_release_check
    CHECK (btrim(client_release) <> ''),
  CONSTRAINT client_signal_v2_batches_ingest_release_check
    CHECK (btrim(ingest_release) <> '')
);

CREATE UNIQUE INDEX client_signal_v2_batches_batch_id_unique
  ON ops.client_signal_v2_batches (batch_id);
CREATE INDEX client_signal_v2_batches_received_idx
  ON ops.client_signal_v2_batches (received_at DESC NULLS LAST);

CREATE TABLE ops.client_signal_v2_windows (
  window_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start timestamptz NOT NULL,
  client text NOT NULL,
  client_release text NOT NULL,
  ingest_release text NOT NULL,
  surface text NOT NULL,
  metric text NOT NULL,
  device_group text NOT NULL,
  sample_source text NOT NULL,
  result text NOT NULL,
  reason_code text NOT NULL,
  measurement_kind text NOT NULL,
  metric_name text,
  navigation_id text,
  interaction_id text,
  cache_status text,
  error_class text,
  fingerprint text,
  bucket text NOT NULL,
  observed_count bigint NOT NULL DEFAULT 0,
  occurrence_count bigint NOT NULL DEFAULT 0,
  estimated_count double precision NOT NULL DEFAULT 0,
  value_sum double precision NOT NULL DEFAULT 0,
  first_observed_at timestamptz NOT NULL,
  last_observed_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT client_signal_v2_windows_client_check
    CHECK (client IN ('web', 'wechat_miniprogram')),
  CONSTRAINT client_signal_v2_windows_source_check
    CHECK (sample_source IN ('real', 'synthetic')),
  CONSTRAINT client_signal_v2_windows_result_check
    CHECK (result IN ('ok', 'error', 'timeout', 'auth_error', 'stale', 'unavailable')),
  CONSTRAINT client_signal_v2_windows_reason_check
    CHECK (reason_code IN ('none', 'auth', 'validation', 'rate_limit', 'client_abort', 'upstream_timeout', 'connection', 'unavailable', 'unknown')),
  CONSTRAINT client_signal_v2_windows_measurement_check
    CHECK (measurement_kind IN ('initial_navigation', 'in_page_navigation', 'interaction', 'background_resume', 'missing_start', 'request')),
  CONSTRAINT client_signal_v2_windows_cache_check
    CHECK (cache_status IS NULL OR cache_status IN ('hit', 'miss', 'stale', 'bypass', 'unknown')),
  CONSTRAINT client_signal_v2_windows_correlation_check
    CHECK ((navigation_id IS NULL OR navigation_id ~ '^(nav|interaction|desk|metric)-[A-Za-z0-9_-]{8,52}$') AND (interaction_id IS NULL OR interaction_id ~ '^(nav|interaction|desk|metric)-[A-Za-z0-9_-]{8,52}$')),
  CONSTRAINT client_signal_v2_windows_metric_name_check
    CHECK (metric_name IS NULL OR metric_name ~ '^[A-Za-z0-9._:-]{1,64}$'),
  CONSTRAINT client_signal_v2_windows_count_check
    CHECK (observed_count > 0 AND occurrence_count > 0 AND estimated_count > 0),
  CONSTRAINT client_signal_v2_windows_value_check
    CHECK (value_sum >= 0),
  CONSTRAINT client_signal_v2_windows_dimensions_check
    CHECK (btrim(client_release) <> '' AND btrim(ingest_release) <> '' AND btrim(surface) <> '' AND btrim(metric) <> '' AND btrim(device_group) <> '' AND btrim(bucket) <> ''),
  CONSTRAINT client_signal_v2_windows_error_dimensions_check
    CHECK (metric = 'runtime_error' OR (error_class IS NULL AND fingerprint IS NULL)),
  CONSTRAINT client_signal_v2_windows_error_time_check
    CHECK (first_observed_at <= last_observed_at),
  CONSTRAINT client_signal_v2_windows_identity UNIQUE NULLS NOT DISTINCT (
    window_start, client, client_release, ingest_release, surface, metric,
    device_group, sample_source, result, reason_code, measurement_kind,
    metric_name, navigation_id, interaction_id, cache_status,
    error_class, fingerprint, bucket
  )
);

CREATE INDEX client_signal_v2_windows_client_metric_time_idx
  ON ops.client_signal_v2_windows (client, metric, window_start DESC NULLS LAST);
CREATE INDEX client_signal_v2_windows_retention_idx
  ON ops.client_signal_v2_windows (window_start);

REVOKE ALL ON TABLE ops.client_signal_v2_batches FROM PUBLIC;
GRANT SELECT, INSERT, DELETE ON TABLE ops.client_signal_v2_batches TO letletme_data_writer;
GRANT USAGE, SELECT ON SEQUENCE ops.client_signal_v2_batches_batch_row_id_seq TO letletme_data_writer;
REVOKE ALL ON TABLE ops.client_signal_v2_batches FROM letletme_graphql_reader;

REVOKE ALL ON TABLE ops.client_signal_v2_windows FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ops.client_signal_v2_windows TO letletme_data_writer;
GRANT USAGE, SELECT ON SEQUENCE ops.client_signal_v2_windows_window_id_seq TO letletme_data_writer;
REVOKE ALL ON TABLE ops.client_signal_v2_windows FROM letletme_graphql_reader;

-- Migration 0067 enabled RLS for the v1 telemetry tables before these v2
-- tables existed. Apply the same writer-only policy here so the additive
-- tables cannot bypass the application-owned ops boundary.
ALTER TABLE ops.client_signal_v2_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY client_signal_v2_batches_data_writer_all
  ON ops.client_signal_v2_batches
  FOR ALL TO letletme_data_writer
  USING (true)
  WITH CHECK (true);

ALTER TABLE ops.client_signal_v2_windows ENABLE ROW LEVEL SECURITY;
CREATE POLICY client_signal_v2_windows_data_writer_all
  ON ops.client_signal_v2_windows
  FOR ALL TO letletme_data_writer
  USING (true)
  WITH CHECK (true);

COMMIT;
