import { z } from 'zod';

const ElementSchema = z.object({
  chance_of_playing_next_round: z.nullable(z.number()),
  chance_of_playing_this_round: z.nullable(z.number()),
  code: z.number(),
  cost_change_event: z.number(),
  cost_change_event_fall: z.number(),
  cost_change_start: z.number(),
  cost_change_start_fall: z.number(),
  dreamteam_count: z.number(),
  element_type: z.number(),
  ep_next: z.nullable(z.string()),
  ep_this: z.nullable(z.string()),
  event_points: z.number(),
  first_name: z.string(),
  form: z.nullable(z.string()),
  id: z.number(),
  in_dreamteam: z.boolean(),
  news: z.string(),
  news_added: z.nullable(z.string()),
  now_cost: z.number(),
  photo: z.string(),
  points_per_game: z.string(),
  second_name: z.string(),
  selected_by_percent: z.string(),
  special: z.boolean(),
  squad_number: z.nullable(z.number()),
  status: z.string(),
  team: z.number(),
  team_code: z.number(),
  total_points: z.number(),
  transfers_in: z.number(),
  transfers_in_event: z.number(),
  transfers_out: z.number(),
  transfers_out_event: z.number(),
  value_form: z.string(),
  value_season: z.string(),
  web_name: z.string(),
  minutes: z.number(),
  goals_scored: z.number(),
  assists: z.number(),
  clean_sheets: z.number(),
  goals_conceded: z.number(),
  own_goals: z.number(),
  penalties_saved: z.number(),
  penalties_missed: z.number(),
  yellow_cards: z.number(),
  red_cards: z.number(),
  saves: z.number(),
  bonus: z.number(),
  bps: z.number(),
  influence: z.string(),
  creativity: z.string(),
  threat: z.string(),
  ict_index: z.string(),
  starts: z.number(),
  expected_goals: z.string(),
  expected_assists: z.string(),
  expected_goal_involvements: z.string(),
  expected_goals_conceded: z.string(),
  influence_rank: z.nullable(z.number()),
  influence_rank_type: z.nullable(z.number()),
  creativity_rank: z.nullable(z.number()),
  creativity_rank_type: z.nullable(z.number()),
  threat_rank: z.nullable(z.number()),
  threat_rank_type: z.nullable(z.number()),
  ict_index_rank: z.nullable(z.number()),
  ict_index_rank_type: z.nullable(z.number()),
  corners_and_indirect_freekicks_order: z.nullable(z.number()),
  corners_and_indirect_freekicks_text: z.string(),
  direct_freekicks_order: z.nullable(z.number()),
  direct_freekicks_text: z.string(),
  penalties_order: z.nullable(z.number()),
  penalties_text: z.string(),
  expected_goals_per_90: z.number(),
  saves_per_90: z.number(),
  expected_assists_per_90: z.number(),
  expected_goal_involvements_per_90: z.number(),
  expected_goals_conceded_per_90: z.number(),
  goals_conceded_per_90: z.number(),
  now_cost_rank: z.nullable(z.number()),
  now_cost_rank_type: z.nullable(z.number()),
  form_rank: z.nullable(z.number()),
  form_rank_type: z.nullable(z.number()),
  points_per_game_rank: z.nullable(z.number()),
  points_per_game_rank_type: z.nullable(z.number()),
  selected_rank: z.nullable(z.number()),
  selected_rank_type: z.nullable(z.number()),
  starts_per_90: z.number(),
  clean_sheets_per_90: z.number(),
});

const ElementsSchema = z.array(ElementSchema);

type Element = z.infer<typeof ElementSchema>;

type Elements = z.infer<typeof ElementsSchema>;

export { Element, Elements, ElementSchema, ElementsSchema };
