import { RawEventLive } from 'src/types/domain/event-live.type';

import { EventLiveCreateInput, PrismaEventLive, PrismaEventLiveCreateInput } from './types';

export const mapPrismaEventLiveToDomain = (prismaEventLive: PrismaEventLive): RawEventLive => ({
  eventId: prismaEventLive.eventId,
  elementId: prismaEventLive.elementId,
  minutes: prismaEventLive.minutes,
  goalsScored: prismaEventLive.goalsScored,
  assists: prismaEventLive.assists,
  cleanSheets: prismaEventLive.cleanSheets,
  goalsConceded: prismaEventLive.goalsConceded,
  ownGoals: prismaEventLive.ownGoals,
  penaltiesSaved: prismaEventLive.penaltiesSaved,
  penaltiesMissed: prismaEventLive.penaltiesMissed,
  yellowCards: prismaEventLive.yellowCards,
  redCards: prismaEventLive.redCards,
  saves: prismaEventLive.saves,
  bonus: prismaEventLive.bonus,
  bps: prismaEventLive.bps,
  starts: prismaEventLive.starts,
  expectedGoals: prismaEventLive.expectedGoals,
  expectedAssists: prismaEventLive.expectedAssists,
  expectedGoalInvolvements: prismaEventLive.expectedGoalInvolvements,
  expectedGoalsConceded: prismaEventLive.expectedGoalsConceded,
  mngWin: prismaEventLive.mngWin,
  mngDraw: prismaEventLive.mngDraw,
  mngLoss: prismaEventLive.mngLoss,
  mngUnderdogWin: prismaEventLive.mngUnderdogWin,
  mngUnderdogDraw: prismaEventLive.mngUnderdogDraw,
  mngCleanSheets: prismaEventLive.mngCleanSheets,
  mngGoalsScored: prismaEventLive.mngGoalsScored,
  inDreamTeam: prismaEventLive.inDreamTeam,
  totalPoints: prismaEventLive.totalPoints,
});

export const mapDomainEventLiveToPrismaCreate = (
  domainEventLive: EventLiveCreateInput,
): PrismaEventLiveCreateInput => ({
  eventId: domainEventLive.eventId,
  elementId: domainEventLive.elementId,
  minutes: domainEventLive.minutes,
  goalsScored: domainEventLive.goalsScored,
  assists: domainEventLive.assists,
  cleanSheets: domainEventLive.cleanSheets,
  goalsConceded: domainEventLive.goalsConceded,
  ownGoals: domainEventLive.ownGoals,
  penaltiesSaved: domainEventLive.penaltiesSaved,
  penaltiesMissed: domainEventLive.penaltiesMissed,
  yellowCards: domainEventLive.yellowCards,
  redCards: domainEventLive.redCards,
  saves: domainEventLive.saves,
  bonus: domainEventLive.bonus,
  bps: domainEventLive.bps,
  starts: domainEventLive.starts,
  expectedGoals: domainEventLive.expectedGoals,
  expectedAssists: domainEventLive.expectedAssists,
  expectedGoalInvolvements: domainEventLive.expectedGoalInvolvements,
  expectedGoalsConceded: domainEventLive.expectedGoalsConceded,
  mngWin: domainEventLive.mngWin,
  mngDraw: domainEventLive.mngDraw,
  mngLoss: domainEventLive.mngLoss,
  mngUnderdogWin: domainEventLive.mngUnderdogWin,
  mngUnderdogDraw: domainEventLive.mngUnderdogDraw,
  mngCleanSheets: domainEventLive.mngCleanSheets,
  mngGoalsScored: domainEventLive.mngGoalsScored,
  inDreamTeam: domainEventLive.inDreamTeam,
  totalPoints: domainEventLive.totalPoints,
});
