import { PlayerStat as PrismaPlayerStatType } from '@prisma/client';
import { PrismaPlayerStatCreateInput } from 'src/repositories/player-stat/type';
import { PlayerStat } from 'src/types/domain/player-stat.type';

export const mapPrismaPlayerStatToDomain = (
  prismaPlayerStat: PrismaPlayerStatType,
): PlayerStat => ({
  event: prismaPlayerStat.event,
  element: prismaPlayerStat.element,
  totalPoints: prismaPlayerStat.totalPoints ?? null,
  form: prismaPlayerStat.form ?? null,
  influence: prismaPlayerStat.influence ?? null,
  creativity: prismaPlayerStat.creativity ?? null,
  threat: prismaPlayerStat.threat ?? null,
  ictIndex: prismaPlayerStat.ictIndex ?? null,
  expectedGoals: prismaPlayerStat.expectedGoals ?? null,
  expectedAssists: prismaPlayerStat.expectedAssists ?? null,
  expectedGoalInvolvements: prismaPlayerStat.expectedGoalInvolvements ?? null,
  expectedGoalsConceded: prismaPlayerStat.expectedGoalsConceded ?? null,
  minutes: prismaPlayerStat.minutes ?? null,
  goalsScored: prismaPlayerStat.goalsScored ?? null,
  assists: prismaPlayerStat.assists ?? null,
  cleanSheets: prismaPlayerStat.cleanSheets ?? null,
  goalsConceded: prismaPlayerStat.goalsConceded ?? null,
  ownGoals: prismaPlayerStat.ownGoals ?? null,
  penaltiesSaved: prismaPlayerStat.penaltiesSaved ?? null,
  yellowCards: prismaPlayerStat.yellowCards ?? null,
  redCards: prismaPlayerStat.redCards ?? null,
  saves: prismaPlayerStat.saves ?? null,
  bonus: prismaPlayerStat.bonus ?? null,
  bps: prismaPlayerStat.bps ?? null,
  starts: prismaPlayerStat.starts ?? null,
  influenceRank: prismaPlayerStat.influenceRank ?? null,
  influenceRankType: prismaPlayerStat.influenceRankType ?? null,
  creativityRank: prismaPlayerStat.creativityRank ?? null,
  creativityRankType: prismaPlayerStat.creativityRankType ?? null,
  threatRank: prismaPlayerStat.threatRank ?? null,
  threatRankType: prismaPlayerStat.threatRankType ?? null,
  ictIndexRank: prismaPlayerStat.ictIndexRank ?? null,
  ictIndexRankType: prismaPlayerStat.ictIndexRankType ?? null,
  mngWin: prismaPlayerStat.mngWin ?? null,
  mngDraw: prismaPlayerStat.mngDraw ?? null,
  mngLoss: prismaPlayerStat.mngLoss ?? null,
  mngUnderdogWin: prismaPlayerStat.mngUnderdogWin ?? null,
  mngUnderdogDraw: prismaPlayerStat.mngUnderdogDraw ?? null,
  mngCleanSheets: prismaPlayerStat.mngCleanSheets ?? null,
  mngGoalsScored: prismaPlayerStat.mngGoalsScored ?? null,
});

export const mapDomainStatToPrismaCreateInput = (
  domainStat: Omit<PlayerStat, 'id'>,
): PrismaPlayerStatCreateInput => ({
  event: domainStat.event,
  element: domainStat.element,
  totalPoints: domainStat.totalPoints,
  form: domainStat.form,
  influence: domainStat.influence,
  creativity: domainStat.creativity,
  threat: domainStat.threat,
  ictIndex: domainStat.ictIndex,
  expectedGoals: domainStat.expectedGoals ?? null,
  expectedAssists: domainStat.expectedAssists ?? null,
  expectedGoalInvolvements: domainStat.expectedGoalInvolvements ?? null,
  expectedGoalsConceded: domainStat.expectedGoalsConceded ?? null,
  minutes: domainStat.minutes,
  goalsScored: domainStat.goalsScored,
  assists: domainStat.assists,
  cleanSheets: domainStat.cleanSheets,
  goalsConceded: domainStat.goalsConceded,
  ownGoals: domainStat.ownGoals,
  penaltiesSaved: domainStat.penaltiesSaved,
  yellowCards: domainStat.yellowCards,
  redCards: domainStat.redCards,
  saves: domainStat.saves,
  bonus: domainStat.bonus,
  bps: domainStat.bps,
  starts: domainStat.starts,
  influenceRank: domainStat.influenceRank,
  influenceRankType: domainStat.influenceRankType,
  creativityRank: domainStat.creativityRank,
  creativityRankType: domainStat.creativityRankType,
  threatRank: domainStat.threatRank,
  threatRankType: domainStat.threatRankType,
  ictIndexRank: domainStat.ictIndexRank,
  ictIndexRankType: domainStat.ictIndexRankType,
});
