import { PlayerStat as PrismaPlayerStatType } from '@prisma/client';
import { PrismaPlayerStatCreateInput } from 'src/repositories/player-stat/type';
import { PlayerStat, PlayerStatId } from 'src/types/domain/player-stat.type';

export const mapPrismaPlayerStatToDomain = (
  prismaPlayerStat: PrismaPlayerStatType,
): PlayerStat => ({
  id: prismaPlayerStat.id.toString() as PlayerStatId,
  eventId: prismaPlayerStat.eventId,
  elementId: prismaPlayerStat.elementId,
  teamId: prismaPlayerStat.teamId,
  form: prismaPlayerStat.form ?? null,
  influence: prismaPlayerStat.influence ?? null,
  creativity: prismaPlayerStat.creativity ?? null,
  threat: prismaPlayerStat.threat ?? null,
  ictIndex: prismaPlayerStat.ictIndex ?? null,
  expectedGoals: prismaPlayerStat.expectedGoals ?? null,
  expectedAssists: prismaPlayerStat.expectedAssists ?? null,
  expectedGoalInvolvements: prismaPlayerStat.expectedGoalInvolvements ?? null,
  expectedGoalsConceded: prismaPlayerStat.expectedGoalsConceded ?? null,
  minutes: prismaPlayerStat.minutes ?? null,
  goalsScored: prismaPlayerStat.goalsScored ?? null,
  assists: prismaPlayerStat.assists ?? null,
  cleanSheets: prismaPlayerStat.cleanSheets ?? null,
  goalsConceded: prismaPlayerStat.goalsConceded ?? null,
  ownGoals: prismaPlayerStat.ownGoals ?? null,
  penaltiesSaved: prismaPlayerStat.penaltiesSaved ?? null,
  yellowCards: prismaPlayerStat.yellowCards ?? null,
  redCards: prismaPlayerStat.redCards ?? null,
  saves: prismaPlayerStat.saves ?? null,
  bonus: prismaPlayerStat.bonus ?? null,
  bps: prismaPlayerStat.bps ?? null,
  starts: prismaPlayerStat.starts ?? null,
  influenceRank: prismaPlayerStat.influenceRank ?? null,
  influenceRankType: prismaPlayerStat.influenceRankType ?? null,
  creativityRank: prismaPlayerStat.creativityRank ?? null,
  creativityRankType: prismaPlayerStat.creativityRankType ?? null,
  threatRank: prismaPlayerStat.threatRank ?? null,
  threatRankType: prismaPlayerStat.threatRankType ?? null,
  ictIndexRank: prismaPlayerStat.ictIndexRank ?? null,
  ictIndexRankType: prismaPlayerStat.ictIndexRankType ?? null,
  expectedGoalsPer90: prismaPlayerStat.expectedGoalsPer90 ?? null,
  savesPer90: prismaPlayerStat.savesPer90 ?? null,
  expectedAssistsPer90: prismaPlayerStat.expectedAssistsPer90 ?? null,
  expectedGoalInvolvementsPer90: prismaPlayerStat.expectedGoalInvolvementsPer90 ?? null,
  totalPoints: prismaPlayerStat.totalPoints ?? null,
});

export const mapDomainStatToPrismaCreateInput = (
  domainStat: Omit<PlayerStat, 'id'>,
): PrismaPlayerStatCreateInput => ({
  eventId: domainStat.eventId,
  elementId: domainStat.elementId,
  teamId: domainStat.teamId,
  form: domainStat.form,
  influence: domainStat.influence,
  creativity: domainStat.creativity,
  threat: domainStat.threat,
  ictIndex: domainStat.ictIndex,
  expectedGoals: domainStat.expectedGoals?.toString() ?? null,
  expectedAssists: domainStat.expectedAssists?.toString() ?? null,
  expectedGoalInvolvements: domainStat.expectedGoalInvolvements?.toString() ?? null,
  expectedGoalsConceded: domainStat.expectedGoalsConceded?.toString() ?? null,
  minutes: domainStat.minutes,
  goalsScored: domainStat.goalsScored,
  assists: domainStat.assists,
  cleanSheets: domainStat.cleanSheets,
  goalsConceded: domainStat.goalsConceded,
  ownGoals: domainStat.ownGoals,
  penaltiesSaved: domainStat.penaltiesSaved,
  yellowCards: domainStat.yellowCards,
  redCards: domainStat.redCards,
  saves: domainStat.saves,
  bonus: domainStat.bonus,
  bps: domainStat.bps,
  starts: domainStat.starts,
  totalPoints: domainStat.totalPoints,
  influenceRank: domainStat.influenceRank,
  influenceRankType: domainStat.influenceRankType,
  creativityRank: domainStat.creativityRank,
  creativityRankType: domainStat.creativityRankType,
  threatRank: domainStat.threatRank,
  threatRankType: domainStat.threatRankType,
  ictIndexRank: domainStat.ictIndexRank,
  ictIndexRankType: domainStat.ictIndexRankType,
  expectedGoalsPer90: domainStat.expectedGoalsPer90?.toString() ?? null,
  savesPer90: domainStat.savesPer90?.toString() ?? null,
  expectedAssistsPer90: domainStat.expectedAssistsPer90?.toString() ?? null,
  expectedGoalInvolvementsPer90: domainStat.expectedGoalInvolvementsPer90?.toString() ?? null,
});
