import {
  PrismaPlayerStat,
  PrismaPlayerStatCreate,
  PrismaPlayerStatCreateInput,
} from 'src/repositories/player-stat/type';
import { PlayerStat, PlayerStatId } from 'src/types/domain/player-stat.type';

export const mapPrismaPlayerStatToDomain = (prismaPlayerStat: PrismaPlayerStat): PlayerStat => ({
  id: prismaPlayerStat.id as PlayerStatId,
  eventId: prismaPlayerStat.eventId,
  elementId: prismaPlayerStat.elementId,
  teamId: prismaPlayerStat.teamId,
  form: prismaPlayerStat.form,
  influence: prismaPlayerStat.influence,
  creativity: prismaPlayerStat.creativity,
  threat: prismaPlayerStat.threat,
  ictIndex: prismaPlayerStat.ictIndex,
  expectedGoals: prismaPlayerStat.expectedGoals,
  expectedAssists: prismaPlayerStat.expectedAssists,
  expectedGoalInvolvements: prismaPlayerStat.expectedGoalInvolvements,
  expectedGoalsConceded: prismaPlayerStat.expectedGoalsConceded,
  minutes: prismaPlayerStat.minutes,
  goalsScored: prismaPlayerStat.goalsScored,
  assists: prismaPlayerStat.assists,
  cleanSheets: prismaPlayerStat.cleanSheets,
  goalsConceded: prismaPlayerStat.goalsConceded,
  ownGoals: prismaPlayerStat.ownGoals,
  penaltiesSaved: prismaPlayerStat.penaltiesSaved,
  yellowCards: prismaPlayerStat.yellowCards,
  redCards: prismaPlayerStat.redCards,
  saves: prismaPlayerStat.saves,
  bonus: prismaPlayerStat.bonus,
  bps: prismaPlayerStat.bps,
  starts: prismaPlayerStat.starts,
  influenceRank: prismaPlayerStat.influenceRank,
  influenceRankType: prismaPlayerStat.influenceRankType,
  creativityRank: prismaPlayerStat.creativityRank,
  creativityRankType: prismaPlayerStat.creativityRankType,
  threatRank: prismaPlayerStat.threatRank,
  threatRankType: prismaPlayerStat.threatRankType,
  ictIndexRank: prismaPlayerStat.ictIndexRank,
  ictIndexRankType: prismaPlayerStat.ictIndexRankType,
  expectedGoalsPer90: prismaPlayerStat.expectedGoalsPer90,
  savesPer90: prismaPlayerStat.savesPer90,
  expectedAssistsPer90: prismaPlayerStat.expectedAssistsPer90,
  expectedGoalInvolvementsPer90: prismaPlayerStat.expectedGoalInvolvementsPer90,
});

export const mapDomainPlayerStatToPrismaCreate = (
  domainPlayerStat: PrismaPlayerStatCreate,
): PrismaPlayerStatCreateInput => ({
  id: domainPlayerStat.id,
  eventId: domainPlayerStat.eventId,
  elementId: domainPlayerStat.elementId,
  teamId: domainPlayerStat.teamId,
  form: domainPlayerStat.form,
  influence: domainPlayerStat.influence,
  creativity: domainPlayerStat.creativity,
  threat: domainPlayerStat.threat,
  ictIndex: domainPlayerStat.ictIndex,
  expectedGoals: domainPlayerStat.expectedGoals,
  expectedAssists: domainPlayerStat.expectedAssists,
  expectedGoalInvolvements: domainPlayerStat.expectedGoalInvolvements,
  expectedGoalsConceded: domainPlayerStat.expectedGoalsConceded,
  minutes: domainPlayerStat.minutes,
  goalsScored: domainPlayerStat.goalsScored,
  assists: domainPlayerStat.assists,
  cleanSheets: domainPlayerStat.cleanSheets,
  goalsConceded: domainPlayerStat.goalsConceded,
  ownGoals: domainPlayerStat.ownGoals,
  penaltiesSaved: domainPlayerStat.penaltiesSaved,
  yellowCards: domainPlayerStat.yellowCards,
  redCards: domainPlayerStat.redCards,
  saves: domainPlayerStat.saves,
  bonus: domainPlayerStat.bonus,
  bps: domainPlayerStat.bps,
  starts: domainPlayerStat.starts,
  influenceRank: domainPlayerStat.influenceRank,
  influenceRankType: domainPlayerStat.influenceRankType,
  creativityRank: domainPlayerStat.creativityRank,
  creativityRankType: domainPlayerStat.creativityRankType,
  threatRank: domainPlayerStat.threatRank,
  threatRankType: domainPlayerStat.threatRankType,
  ictIndexRank: domainPlayerStat.ictIndexRank,
  ictIndexRankType: domainPlayerStat.ictIndexRankType,
  expectedGoalsPer90: domainPlayerStat.expectedGoalsPer90,
  savesPer90: domainPlayerStat.savesPer90,
  expectedAssistsPer90: domainPlayerStat.expectedAssistsPer90,
  expectedGoalInvolvementsPer90: domainPlayerStat.expectedGoalInvolvementsPer90,
});
